import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutClient from "./LayoutClient";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/Footer"; // Import your Footer component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KickOffGear",
  description: "Generated by create next app",
  icons: "icon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <LayoutClient>
          <div className="flex-grow">{children}</div>
        </LayoutClient>
      </body>
    </html>
  );
}
